### ISSUE TITLE
Loading a generated PKL file into the SMPL Blender Addon results in an error

### ISSUE THREAD

**Issue by garg** [kbrodt/sketch2pose#4]
When I load a S2P generated PKL file into the SMPL Blender Addon from https://smpl-x.is.tue.mpg.de/download.php I receive a key error. Is this an issue with the generated PKL file or the Blender Addon? 

```
Traceback (most recent call last):
  File "/Users/username/Library/Application Support/Blender/3.2/scripts/addons/smplx_blender_addon/__init__.py", line 851, in execute
    jaw_pose = np.array(data["jaw_pose"]).reshape(3)
KeyError: 'jaw_pose'
```

If I open the above referenced __init__.py and comment out the following lines: 

```
            # jaw_pose = np.array(data["jaw_pose"]).reshape(3)
            # expression = np.array(data["expression"]).reshape(-1).tolist()
```

Then the pose loads though it's upside down. 

Is anyone else experiencing this issue?

**Comment by kbrodt** [comment]
It's not an error. We don't have any `jaw_pose` and `expression`. So it's ok to comment these lines in SMPL blender addon.

The upside down rotation apears due to different coordinate system of image space (x right, y **down**) and normal coordinate system (x right, y **up**). You can force to rotate `global_orient` by `pi` over `x` axis, I guess.

**Comment by garg** [comment]
Thank you! That works!

Closing this issue now.
